# The logging configuration. On a real server this will be a file url. e.g. file://{{ mujina_dir }}/logback.xml
logging:
  config: classpath:logback.xml

server:
  # The port to where this Spring Boot application listens to. e.g. http://localhost:{{ springapp_tcpport }}
  port: 9090
  servlet:
    # The context path of the server. You can skip this value in the overriding application.yml on the classpath
    context-path:
    session:
      # 8 hours before we time-out
      timeout: 28800

secure_cookie: false

sp:
  # base url
  base_url: https://signin.aws.amazon.com
  # Entity ID of the SP
  entity_id: urn:amazon:webservices
  # Private key used to sign the SAML response
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDWsri5GYcdvzWb07gQDtkCTuXBKohy0QBUOH2yvB6PE2abA5HPVjdy/0kU39SJxw1OkGBXRo+oDM/JeGWW+U6flEtozyNwEGIh08WLkLr7qABTx1uTGT2hZl41Trz4OunhBcRVTW2tROaPlNro4nR2UT8Xz2enrZlV9WNYeI5M6ekOMHMgUwV6TqAPnPc2BLOZH0TqK8RydzEgf7iywYMlbrgOzg11hAAK45C+q4hFWH59roA45uF2FNC4F+U+BgroQt2X0QLAmxzptxb5vuG3cOI8a76GhFKUVCTQBe1gJIUfzc+hYwRcqd0636YhNKS1cxmcXh0CSH6+of4ykjq1AgMBAAECggEAO2dFzwkuJl/iYFQrKF5DUu0ris/O4x3K3oKm3M5KEkJG8HsDW/+55dqWiO0JbHmjx+oQjfVbCB9LWq4yRZyDUYoBd2Vgo8AUttFWZjBMXBb2yDdvsfqY39BoHo3DoVcDoRwsX4HF59wZgv6ntyn5GUePknHzdySEOZFkxHTOwp6v+0ei6ryDKCvNniB+NTnIG2eP8hF6csXI4QLzs2Qcz1li1ckS7OOrGwofSqimhVkISJCJjFbniuki8AV+5rhrKHw1qhIpiG1Pp/nA63fRQWGUfytl0iO3+Bhm4R3tUfGh+sk0ngx137CIZ6wR/oZWSucaFshqtH14bd1gKRnEHQKBgQDtkYA12zcXvU5kfHRVTdCuuVHfO45eyTbyOftTcW8hnEwjl7G4Fh36haOCqCekCTYCKTlQ4Sb3TV8Mp4UJ87vggDYCJZIKXKDSj1Wnc9nLkq5vmcA0qczDUP23x4Oq89zHdbXzys51uhISazfSfc/nWZCAlPAaGR4wnNrLp5ohDwKBgQDnWvry0itN+Gx6SZ3ykQ2yxqYdwa6gtnnk35oOdBQML7k+XzI8BHTqgMHrxTmg+isEoT9hR5BseEwU1L/+HbNqlnqUWDNta28kp3kDlqgSo7lmYnacUiDHYmRKQOYCqxdqlriHaNc5F7WYAxSU52xLm4mHK+c8JWdk/4uBrl0f+wKBgFb5MsAEzmmhg6akLY7hWynsbL3WNuwarEQH2CwXVkEu0G0jZwvnBPinnlICL+kM+jnWT8Z9d1+IcujWF42qLrklFyC4Enw6pyIPGaOhdTXjMHtpBYYCOBW1e/2hTGH0v3pCbOeg8u8EvQMDP7+PEeM31gBNBo33bicL9cojRPkfAoGASmtIl70lMuJ7OmbdyL4CEwS1QJMhsg6gbQ/EBWwvWrArPTXv+cBRP3GFb2q0m+R82/NmaMtVWJ7lkjnRPFOfd+TJr1gjysmpKbg5Q/89Nym1JIr9rlD4vEoZCo2Pr0ILuTycROpjeLj4r9olz7QVcMiqV3G24vEBLkrJPECzMesCgYEAv1FaPoT1kCQAcRbP1SV1gYRgThIkXqxJN+yfJYHAz/ynPNEt+ausVkDlTBT+e0eq0ClECDqK0wNPBICovU7GNq2gvhP4CNnrbhziCa5XbyJBO9K+pLBYv+Ez1I+hfzX14gruBpyTD7RctmS8FjhfFw2VH7O6FEbKuXeo5aiez/8=
  # Public certificate to verify the signature of the SAML response
  certificate: MIIDfzCCAmegAwIBAgIUHYDpuOwwPOQWJyG7S6QWaCLcPo4wDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCQ04xCzAJBgNVBAgMAkpTMQswCQYDVQQHDAJOSjEVMBMGA1UECgwMT3JnYW5pemF0aW9uMQ8wDQYDVQQLDAZNVWppbmEwHhcNMjMwNTEyMDEzNjM4WhcNMzMwNTExMDEzNjM4WjBPMQswCQYDVQQGEwJDTjELMAkGA1UECAwCSlMxCzAJBgNVBAcMAk5KMRUwEwYDVQQKDAxPcmdhbml6YXRpb24xDzANBgNVBAsMBk1VamluYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANayuLkZhx2/NZvTuBAO2QJO5cEqiHLRAFQ4fbK8Ho8TZpsDkc9WN3L/SRTf1InHDU6QYFdGj6gMz8l4ZZb5Tp+US2jPI3AQYiHTxYuQuvuoAFPHW5MZPaFmXjVOvPg66eEFxFVNba1E5o+U2ujidHZRPxfPZ6etmVX1Y1h4jkzp6Q4wcyBTBXpOoA+c9zYEs5kfROorxHJ3MSB/uLLBgyVuuA7ODXWEAArjkL6riEVYfn2ugDjm4XYU0LgX5T4GCuhC3ZfRAsCbHOm3Fvm+4bdw4jxrvoaEUpRUJNAF7WAkhR/Nz6FjBFyp3TrfpiE0pLVzGZxeHQJIfr6h/jKSOrUCAwEAAaNTMFEwHQYDVR0OBBYEFIsQyewJkglfbNyOxT00iEG1yD0ZMB8GA1UdIwQYMBaAFIsQyewJkglfbNyOxT00iEG1yD0ZMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBADhTisryivqGbEjTzOw9xeMu5CQg6XY9BO/4oGdejjDSgCGwIwBxWSsP0f0lAnhJ0j2SLPp6WuJomjyydXMrFRyic6ERXgMIjZTVbTBhNIaDQpPtiq34MLfYwpVE0O7aovDjM7ZJwStnlTnUhzpl/iRuHk+CajUGKlbsu1G8BFWvFJkkUcGjSWUwfbqTBRnO3sNmo9FZkRG5gFoiegVkH7Gz8ug+XX0pB9YbYZ5Is9pgmP7t5c4JIwkxeSLcnS/erY7JrukLVsEwP54QYbywfj8K3KGMe0vba9gMHoVBMZhGAdeMp8Zy0hGFrYloopKkBKbdk3NSVJmAA+NNxrakBn0=
  # Passphrase of the keystore
  passphrase: secret
  # Resource URL for the idp metadata
  idp_metadata_url: classpath:metadata/mujina.local.idp.metadata.xml
  # SingleSignOnServiceLocation
  single_sign_on_service_location: https://aws-saml.okya.io/SingleSignOnService
  # ACS location
  acs_location_path: /saml
  # Protocol binding
  protocol_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  # Do we sign the authnRequest
  needs_signing: true
  # Are endpoints compared. If so then pay notice to the base_url when behind a load balancer
  compare_endpoints: true


spring:
  velocity:
    check-template-location: False

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

# We disable all endpoints except health for the load-balancer and info for git information.
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full
